### ISSUE TITLE
js-controller crashes when adapter stopped

### ISSUE THREAD

**Issue by MeisterTR** [iobroker-community-adapters/ioBroker.proxmox#16]
Beim Ausschalten des adapters (compact mode) stürtzt alles ab.

admin.0 | 2019-02-16 20:22:05.415 | error | at _combinedTickCallback (internal/process/next_tick.js:139:11)
-- | -- | -- | --
admin.0 | 2019-02-16 20:22:05.415 | error | at emitErrorNT (internal/streams/destroy.js:66:8)
admin.0 | 2019-02-16 20:22:05.415 | error | at Socket.emit (events.js:211:7)
admin.0 | 2019-02-16 20:22:05.415 | error | at emitOne (events.js:116:13)
admin.0 | 2019-02-16 20:22:05.415 | error | at WebSocket.finalize (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/ws/lib/WebSocket.js:182:41)
admin.0 | 2019-02-16 20:22:05.415 | error | at WebSocket.emit (events.js:211:7)
admin.0 | 2019-02-16 20:22:05.415 | error | at emitOne (events.js:116:13)
admin.0 | 2019-02-16 20:22:05.415 | error | at WebSocket.onError (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/ws/lib/EventTarget.js:109:16)
admin.0 | 2019-02-16 20:22:05.415 | error | at WebSocket.ws.onerror (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/engine.io-client/lib/transports/websocket.js:150:10)
admin.0 | 2019-02-16 20:22:05.415 | error | at WS.Transport.onError (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/engine.io-client/lib/transport.js:64:13)
admin.0 | 2019-02-16 20:22:05.415 | error | Error: websocket error
admin.0 | 2019-02-16 20:22:05.414 | error | websocket error
proxmox.0 | 2019-02-16 20:22:05.406 | error | uncaught exception: Cannot read property 'pushLog' of null
javascript.0 | 2019-02-16 20:22:05.405 | error | uncaught exception: Cannot read property 'pushLog' of null
host.cmbroker | 2019-02-16 20:22:05.392 | info | instance system.adapter.proxmox.0 terminated with code undefined ()
  | 2019-02-16 20:22:05.391 | info | erminating
host.cmbroker | 2019-02-16 20:22:05.390 | info | stopInstance system.adapter.proxmox.0 killing pid undefined
host.cmbroker | 2019-02-16 20:22:05.390 | info | stopInstance system.adapter.proxmox.0

der code ist im cm brnach

**Comment by MeisterTR** [comment]
fixed in 1.0.1
