### ISSUE TITLE
error while restore

### ISSUE THREAD

**Issue by MeisterTR** [iobroker-community-adapters/ioBroker.proxmox#33]
proxmox.0 | 2019-09-29 06:11:13.460 | error | at IncomingMessage.emit (events.js:203:15)
-- | -- | -- | --
proxmox.0 | 2019-09-29 06:11:13.460 | error | at Object.onceWrapper (events.js:286:20)
proxmox.0 | 2019-09-29 06:11:13.460 | error | at IncomingMessage.<anonymous> (/opt/iobroker/node_modules/iobroker.proxmox/node_modules/request/request.js:1083:12)
proxmox.0 | 2019-09-29 06:11:13.460 | error | at Request.emit (events.js:198:13)
proxmox.0 | 2019-09-29 06:11:13.460 | error | at Request.<anonymous> (/opt/iobroker/node_modules/iobroker.proxmox/node_modules/request/request.js:1161:10)
proxmox.0 | 2019-09-29 06:11:13.460 | error | at Request.emit (events.js:198:13)
proxmox.0 | 2019-09-29 06:11:13.460 | error | at Request.self.callback (/opt/iobroker/node_modules/iobroker.proxmox/node_modules/request/request.js:185:22)
proxmox.0 | 2019-09-29 06:11:13.460 | error | at Request.request [as _callback] (/opt/iobroker/node_modules/iobroker.proxmox/lib/proxmox.js:166:21)
proxmox.0 | 2019-09-29 06:11:13.460 | error | at _get.then.data (/opt/iobroker/node_modules/iobroker.proxmox/lib/proxmox.js:48:9)
proxmox.0 | 2019-09-29 06:11:13.460 | error | at /opt/iobroker/node_modules/iobroker.proxmox/main.js:415:33
proxmox.0 | 2019-09-29 06:11:13.460 | error | TypeError: Cannot read property 'name' of undefined
proxmox.0 | 2019-09-29 06:11:13.452 | error | uncaught exception: Cannot read property 'name' of undefined

**Comment by MeisterTR** [comment]
should be fixed now
