### ISSUE TITLE
error: restart adapter uncaught exception uptime of undefined

### ISSUE THREAD

**Issue by Ilovegym66** [iobroker-community-adapters/ioBroker.proxmox#54]
Hi, Version 1.0.1 ( und alle vorher auch schon):
`ilovegym@iobroker /opt/iobroker/log $ cat iobroker.2020-03-10.log | grep proxmox2020-03-10 05:06:55.241  - info: host.iobroker "system.adapter.proxmox.0" enabled
2020-03-10 05:06:55.300  - info: host.iobroker instance system.adapter.proxmox.0 started with pid 18409
2020-03-10 05:40:32.652  - error: proxmox.0 (18409) uncaught exception: Cannot read property 'uptime' of undefined
2020-03-10 05:40:32.655  - error: proxmox.0 (18409) TypeError: Cannot read property 'uptime' of undefined
    at /opt/iobroker/node_modules/iobroker.proxmox/main.js:380:34
    at _get.then.data (/opt/iobroker/node_modules/iobroker.proxmox/lib/proxmox.js:43:9)
    at Request.request [as _callback] (/opt/iobroker/node_modules/iobroker.proxmox/lib/proxmox.js:167:21)
2020-03-10 05:40:33.194  - error: host.iobroker Caught by controller[0]:     at /opt/iobroker/node_modules/iobroker.proxmox/main.js:380:34
2020-03-10 05:40:33.194  - error: host.iobroker Caught by controller[0]:     at _get.then.data (/opt/iobroker/node_modules/iobroker.proxmox/lib/proxmox.js:43:9)
2020-03-10 05:40:33.194  - error: host.iobroker Caught by controller[0]:     at Request.request [as _callback] (/opt/iobroker/node_modules/iobroker.proxmox/lib/proxmox.js:167:21)
2020-03-10 05:40:33.195  - info: host.iobroker instance system.adapter.proxmox.0 terminated with code 0 (NO_ERROR)
2020-03-10 05:40:33.195  - info: host.iobroker Restart adapter system.adapter.proxmox.0 because enabled
2020-03-10 05:41:03.219  - info: host.iobroker instance system.adapter.proxmox.0 started with pid 24036
2020-03-10 07:15:35.221  - error: proxmox.0 (24036) uncaught exception: Cannot read property 'uptime' of undefined
2020-03-10 07:15:35.223  - error: proxmox.0 (24036) TypeError: Cannot read property 'uptime' of undefined
    at /opt/iobroker/node_modules/iobroker.proxmox/main.js:380:34
    at _get.then.data (/opt/iobroker/node_modules/iobroker.proxmox/lib/proxmox.js:43:9)
    at Request.request [as _callback] (/opt/iobroker/node_modules/iobroker.proxmox/lib/proxmox.js:167:21)
2020-03-10 07:15:35.795  - error: host.iobroker Caught by controller[0]:     at /opt/iobroker/node_modules/iobroker.proxmox/main.js:380:34
2020-03-10 07:15:35.796  - error: host.iobroker Caught by controller[0]:     at _get.then.data (/opt/iobroker/node_modules/iobroker.proxmox/lib/proxmox.js:43:9)
2020-03-10 07:15:35.796  - error: host.iobroker Caught by controller[0]:     at Request.request [as _callback] (/opt/iobroker/node_modules/iobroker.proxmox/lib/proxmox.js:167:21)
2020-03-10 07:15:35.796  - info: host.iobroker instance system.adapter.proxmox.0 terminated with code 0 (NO_ERROR)
2020-03-10 07:15:35.796  - info: host.iobroker Restart adapter system.adapter.proxmox.0 because enabled
2020-03-10 07:16:05.823  - info: host.iobroker instance system.adapter.proxmox.0 started with pid 7544
2020-03-10 07:16:22.403  - error: proxmox.0 (7544) uncaught exception: Cannot read property 'name' of undefined
2020-03-10 07:16:22.404  - error: proxmox.0 (7544) TypeError: Cannot read property 'name' of undefined
    at /opt/iobroker/node_modules/iobroker.proxmox/main.js:467:74
    at _get.then.data (/opt/iobroker/node_modules/iobroker.proxmox/lib/proxmox.js:49:9)
    at Request.request [as _callback] (/opt/iobroker/node_modules/iobroker.proxmox/lib/proxmox.js:167:21)
2020-03-10 07:16:23.029  - error: host.iobroker Caught by controller[0]:     at /opt/iobroker/node_modules/iobroker.proxmox/main.js:467:74
2020-03-10 07:16:23.029  - error: host.iobroker Caught by controller[0]:     at _get.then.data (/opt/iobroker/node_modules/iobroker.proxmox/lib/proxmox.js:49:9)
2020-03-10 07:16:23.029  - error: host.iobroker Caught by controller[0]:     at Request.request [as _callback] (/opt/iobroker/node_modules/iobroker.proxmox/lib/proxmox.js:167:21)
2020-03-10 07:16:23.030  - info: host.iobroker instance system.adapter.proxmox.0 terminated with code 0 (NO_ERROR)
2020-03-10 07:16:23.030  - info: host.iobroker Restart adapter system.adapter.proxmox.0 because enabled
2020-03-10 07:16:53.047  - info: host.iobroker instance system.adapter.proxmox.0 started with pid 7703
2020-03-10 07:17:05.024  - error: proxmox.0 (7703) uncaught exception: Cannot read property 'name' of undefined
2020-03-10 07:17:05.028  - error: proxmox.0 (7703) TypeError: Cannot read property 'name' of undefined
    at /opt/iobroker/node_modules/iobroker.proxmox/main.js:467:74
    at _get.then.data (/opt/iobroker/node_modules/iobroker.proxmox/lib/proxmox.js:49:9)
    at Request.request [as _callback] (/opt/iobroker/node_modules/iobroker.proxmox/lib/proxmox.js:167:21)
2020-03-10 07:17:05.646  - error: host.iobroker Caught by controller[0]:     at /opt/iobroker/node_modules/iobroker.proxmox/main.js:467:74
2020-03-10 07:17:05.646  - error: host.iobroker Caught by controller[0]:     at _get.then.data (/opt/iobroker/node_modules/iobroker.proxmox/lib/proxmox.js:49:9)
2020-03-10 07:17:05.646  - error: host.iobroker Caught by controller[0]:     at Request.request [as _callback] (/opt/iobroker/node_modules/iobroker.proxmox/lib/proxmox.js:167:21)
2020-03-10 07:17:05.647  - info: host.iobroker instance system.adapter.proxmox.0 terminated with code 0 (NO_ERROR)
2020-03-10 07:17:05.647  - info: host.iobroker Restart adapter system.adapter.proxmox.0 because enabled
2020-03-10 07:17:35.664  - info: host.iobroker instance system.adapter.proxmox.0 started with pid 7863
2020-03-10 07:41:30.818  - info: host.iobroker "system.adapter.proxmox.0" disabled
2020-03-10 07:41:30.819  - info: host.iobroker stopInstance system.adapter.proxmox.0 (force=false, process=true)
2020-03-10 07:41:30.819  - info: host.iobroker stopInstance system.adapter.proxmox.0 send kill signal
2020-03-10 07:41:31.350  - info: host.iobroker instance system.adapter.proxmox.0 terminated with code 156 (156)
`

**Comment by Feuer-sturm** [comment]
Ich habe proxmox Adapter 1.0.2 installiert.
Wenn ich den laufenden Adapter beende und neu starte bekomme ich auch die untenstehende Fehlermeldungen. Mein NAS war zu diesem Zeitpunkt des Adapter Neustarts ausgeschaltet.
Ich habe in proxmox mein NAS eingebunden, wo die Backups gespeichert werden. Hängt diese Fehlermeldung hiermit zusammen: https://github.com/iobroker-community-adapters/ioBroker.proxmox/issues/50 ?
Wenn mein NAS wieder online ist und ich den proxmox Adapter neu starte bekomme ich keine Fehlermeldungen.

```
proxmox.0 | 2020-03-10 19:59:14.984 | info | (26356) starting. Version 1.0.2 in /opt/iobroker/node_modules/iobroker.proxmox, node: v10.18.1
-- | -- | -- | --
host.beebox(iobrokerMaster) | 2020-03-10 19:59:13.039 | info | instance system.adapter.proxmox.0 started with pid 26356
host.beebox(iobrokerMaster) | 2020-03-10 19:58:43.014 | info | Restart adapter system.adapter.proxmox.0 because enabled
host.beebox(iobrokerMaster) | 2020-03-10 19:58:43.014 | info | instance system.adapter.proxmox.0 terminated with code 0 (NO_ERROR)
host.beebox(iobrokerMaster) | 2020-03-10 19:58:43.014 | error | Caught by controller[0]:     at IncomingMessage.emit (events.js:203:15)
host.beebox(iobrokerMaster) | 2020-03-10 19:58:43.014 | error | Caught by controller[0]:     at Object.onceWrapper (events.js:286:20)
host.beebox(iobrokerMaster) | 2020-03-10 19:58:43.013 | error | Caught by controller[0]:     at IncomingMessage.<anonymous> (/opt/iobroker/node_modules/request/request.js:1083:12)
host.beebox(iobrokerMaster) | 2020-03-10 19:58:43.013 | error | Caught by controller[0]:     at Request.emit (events.js:198:13)
host.beebox(iobrokerMaster) | 2020-03-10 19:58:43.013 | error | Caught by controller[0]:     at Request.<anonymous> (/opt/iobroker/node_modules/request/request.js:1161:10)
host.beebox(iobrokerMaster) | 2020-03-10 19:58:43.013 | error | Caught by controller[0]:     at Request.emit (events.js:198:13)
host.beebox(iobrokerMaster) | 2020-03-10 19:58:43.012 | error | Caught by controller[0]:     at Request.self.callback (/opt/iobroker/node_modules/request/request.js:185:22)
host.beebox(iobrokerMaster) | 2020-03-10 19:58:43.012 | error | Caught  by controller[0]:     at Request.request [as _callback]  (/opt/iobroker/node_modules/iobroker.proxmox/lib/proxmox.js:167:21)
host.beebox(iobrokerMaster) | 2020-03-10 19:58:43.012 | error | Caught by controller[0]:     at _get.then.data (/opt/iobroker/node_modules/iobroker.proxmox/lib/proxmox.js:49:9)
host.beebox(iobrokerMaster) | 2020-03-10 19:58:43.012 | error | Caught by controller[0]:     at /opt/iobroker/node_modules/iobroker.proxmox/main.js:467:74
host.beebox(iobrokerMaster) | 2020-03-10 19:58:43.010 | error | Caught by controller[0]: TypeError: Cannot read property 'name' of undefined
proxmox.0 | 2020-03-10 19:58:42.483 | info | (26341) Terminated (NO_ERROR): Without reason
proxmox.0 | 2020-03-10 19:58:42.482 | info | (26341) terminating
proxmox.0 | 2020-03-10 19:58:42.451 | info | (26341) cleaned everything up...
proxmox.0 | 2020-03-10 19:58:42.450 | error | (26341) TypeError: Cannot read property 'name' of undefined     at /opt/iobroker/node_modules/iobroker.proxmox/main.js:467:74     at _get.then.data (/opt/iobroker/node_modules/iobroker.proxmox/lib/pro
proxmox.0 | 2020-03-10 19:58:42.449 | error | (26341) uncaught exception: Cannot read property 'name' of undefined
javascript.0 | 2020-03-10 19:58:29.880 | info | (21029) script.js.Skripte.Lueftung: Stoßlüfung nicht aktiv, LED ausschalten
proxmox.0 | 2020-03-10 19:58:22.186 | info | (26341) starting. Version 1.0.2 in /opt/iobroker/node_modules/iobroker.proxmox, node: v10.18.1
host.beebox(iobrokerMaster) | 2020-03-10 19:58:20.253 | info | instance system.adapter.proxmox.0 started with pid 26341
host.beebox(iobrokerMaster) | 2020-03-10 19:57:50.227 | info | Restart adapter system.adapter.proxmox.0 because enabled
host.beebox(iobrokerMaster) | 2020-03-10 19:57:50.226 | info | instance system.adapter.proxmox.0 terminated with code 0 (NO_ERROR)
host.beebox(iobrokerMaster) | 2020-03-10 19:57:50.226 | error | Caught by controller[1]:     at IncomingMessage.emit (events.js:203:15)
host.beebox(iobrokerMaster) | 2020-03-10 19:57:50.226 | error | Caught by controller[1]:     at Object.onceWrapper (events.js:286:20)
host.beebox(iobrokerMaster) | 2020-03-10 19:57:50.226 | error | Caught by controller[1]:     at IncomingMessage.<anonymous> (/opt/iobroker/node_modules/request/request.js:1083:12)
host.beebox(iobrokerMaster) | 2020-03-10 19:57:50.226 | error | Caught by controller[1]:     at Request.emit (events.js:198:13)
host.beebox(iobrokerMaster) | 2020-03-10 19:57:50.225 | error | Caught by controller[1]:     at Request.<anonymous> (/opt/iobroker/node_modules/request/request.js:1161:10)
host.beebox(iobrokerMaster) | 2020-03-10 19:57:50.225 | error | Caught by controller[1]:     at Request.emit (events.js:198:13)
host.beebox(iobrokerMaster) | 2020-03-10 19:57:50.225 | error | Caught by controller[1]:     at Request.self.callback (/opt/iobroker/node_modules/request/request.js:185:22)
host.beebox(iobrokerMaster) | 2020-03-10 19:57:50.225 | error | Caught  by controller[1]:     at Request.request [as _callback]  (/opt/iobroker/node_modules/iobroker.proxmox/lib/proxmox.js:167:21)
host.beebox(iobrokerMaster) | 2020-03-10 19:57:50.225 | error | Caught by controller[1]:     at _get.then.data (/opt/iobroker/node_modules/iobroker.proxmox/lib/proxmox.js:49:9)
host.beebox(iobrokerMaster) | 2020-03-10 19:57:50.224 | error | Caught by controller[1]:     at /opt/iobroker/node_modules/iobroker.proxmox/main.js:467:74
host.beebox(iobrokerMaster) | 2020-03-10 19:57:50.224 | error | Caught by controller[1]: TypeError: Cannot read property 'name' of undefined
host.beebox(iobrokerMaster) | 2020-03-10 19:57:50.224 | error | Caught by controller[0]:     at IncomingMessage.emit (events.js:203:15)
host.beebox(iobrokerMaster) | 2020-03-10 19:57:50.224 | error | Caught by controller[0]:     at Object.onceWrapper (events.js:286:20)
host.beebox(iobrokerMaster) | 2020-03-10 19:57:50.223 | error | Caught by controller[0]:     at IncomingMessage.<anonymous> (/opt/iobroker/node_modules/request/request.js:1083:12)
host.beebox(iobrokerMaster) | 2020-03-10 19:57:50.223 | error | Caught by controller[0]:     at Request.emit (events.js:198:13)
host.beebox(iobrokerMaster) | 2020-03-10 19:57:50.223 | error | Caught by controller[0]:     at Request.<anonymous> (/opt/iobroker/node_modules/request/request.js:1161:10)
host.beebox(iobrokerMaster) | 2020-03-10 19:57:50.223 | error | Caught by controller[0]:     at Request.emit (events.js:198:13)
host.beebox(iobrokerMaster) | 2020-03-10 19:57:50.222 | error | Caught by controller[0]:     at Request.self.callback (/opt/iobroker/node_modules/request/request.js:185:22)
host.beebox(iobrokerMaster) | 2020-03-10 19:57:50.222 | error | Caught  by controller[0]:     at Request.request [as _callback]  (/opt/iobroker/node_modules/iobroker.proxmox/lib/proxmox.js:167:21)
host.beebox(iobrokerMaster) | 2020-03-10 19:57:50.222 | error | Caught by controller[0]:     at _get.then.data (/opt/iobroker/node_modules/iobroker.proxmox/lib/proxmox.js:49:9)
host.beebox(iobrokerMaster) | 2020-03-10 19:57:50.222 | error | Caught by controller[0]:     at /opt/iobroker/node_modules/iobroker.proxmox/main.js:467:74
host.beebox(iobrokerMaster) | 2020-03-10 19:57:50.221 | error | Caught by controller[0]: TypeError: Cannot read property 'name' of undefined
proxmox.0 | 2020-03-10 19:57:49.693 | info | (26326) Terminated (NO_ERROR): Without reason
proxmox.0 | 2020-03-10 19:57:49.691 | info | (26326) terminating
proxmox.0 | 2020-03-10 19:57:49.648 | error | (26326) TypeError: Cannot read property 'name' of undefined     at /opt/iobroker/node_modules/iobroker.proxmox/main.js:467:74     at _get.then.data (/opt/iobroker/node_modules/iobroker.proxmox/lib/pro
proxmox.0 | 2020-03-10 19:57:49.648 | error | (26326) uncaught exception: Cannot read property 'name' of undefined
proxmox.0 | 2020-03-10 19:57:49.634 | info | (26326) cleaned everything up...
proxmox.0 | 2020-03-10 19:57:49.633 | error | (26326) TypeError: Cannot read property 'name' of undefined     at /opt/iobroker/node_modules/iobroker.proxmox/main.js:467:74     at _get.then.data (/opt/iobroker/node_modules/iobroker.proxmox/lib/pro
proxmox.0 | 2020-03-10 19:57:49.632 | error | (26326) uncaught exception: Cannot read property 'name' of undefined
proxmox.0 | 2020-03-10 19:57:37.721 | info | (26326) starting. Version 1.0.2 in /opt/iobroker/node_modules/iobroker.proxmox, node: v10.18.1
host.beebox(iobrokerMaster) | 2020-03-10 19:57:35.755 | info | instance system.adapter.proxmox.0 started with pid 26326
host.beebox(iobrokerMaster) | 2020-03-10 19:57:35.731 | info | "system.adapter.proxmox.0" enabled
host.beebox(iobrokerMaster) | 2020-03-10 19:57:31.901 | info | instance system.adapter.proxmox.0 terminated with code 156 (156)
proxmox.0 | 2020-03-10 19:57:31.366 | info | (21500) Terminated (START_IMMEDIATELY_AFTER_STOP): Without reason
proxmox.0 | 2020-03-10 19:57:31.364 | info | (21500) terminating
proxmox.0 | 2020-03-10 19:57:31.363 | info | (21500) cleaned everything up...
proxmox.0 | 2020-03-10 19:57:31.360 | info | (21500) Got terminate signal TERMINATE_YOURSELF
host.beebox(iobrokerMaster) | 2020-03-10 19:57:31.357 | info | stopInstance system.adapter.proxmox.0 send kill signal
host.beebox(iobrokerMaster) | 2020-03-10 19:57:31.355 | info | stopInstance system.adapter.proxmox.0 (force=false, process=true)
host.beebox(iobrokerMaster) | 2020-03-10 19:57:31.353 | info | "system.adapter.proxmox.0" disabled
```

**Comment by MeisterTR** [comment]
please try version from git

**Comment by Feuer-sturm** [comment]
Hello @MeisterTR , I just installed the version from Github and I don't have any errors in my log file.
I shutdown my NAS and switched the proxmox adapter off and on again like in my posting before. Everything is fine :-)

**Comment by Ilovegym66** [comment]
Sorry, since some days the error is back:
`

proxmox.0 | 2020-03-26 13:14:54.632 | error | at IncomingMessage.emit (events.js:203:15)
-- | -- | -- | --
proxmox.0 | 2020-03-26 13:14:54.632 | error | at Object.onceWrapper (events.js:286:20)
proxmox.0 | 2020-03-26 13:14:54.632 | error | at IncomingMessage.<anonymous> (/opt/iobroker/node_modules/request/request.js:1083:12)
proxmox.0 | 2020-03-26 13:14:54.632 | error | at Request.emit (events.js:198:13)
proxmox.0 | 2020-03-26 13:14:54.632 | error | at Request.<anonymous> (/opt/iobroker/node_modules/request/request.js:1161:10)
proxmox.0 | 2020-03-26 13:14:54.632 | error | at Request.emit (events.js:198:13)
proxmox.0 | 2020-03-26 13:14:54.632 | error | at Request.self.callback (/opt/iobroker/node_modules/request/request.js:185:22)
proxmox.0 | 2020-03-26 13:14:54.632 | error | at Request.request [as _callback] (/opt/iobroker/node_modules/iobroker.proxmox/lib/proxmox.js:167:21)
proxmox.0 | 2020-03-26 13:14:54.632 | error | at _get.then.data (/opt/iobroker/node_modules/iobroker.proxmox/lib/proxmox.js:43:9)
proxmox.0 | 2020-03-26 13:14:54.632 | error | at /opt/iobroker/node_modules/iobroker.proxmox/main.js:380:34
proxmox.0 | 2020-03-26 13:14:54.632 | error | (4373) TypeError: Cannot read property 'uptime' of undefined
proxmox.0 | 2020-03-26 13:14:54.631 | error | (4373) uncaught exception: Cannot read property 'uptime' of undefined

`
