### ISSUE TITLE
Unhandled promise rejection mit anschließendem Unable to authenticate with Proxmox host

### ISSUE THREAD

**Issue by Feuer-sturm** [iobroker-community-adapters/ioBroker.proxmox#82]
Ich hab seit langer Zeit den proxmox Adapter am laufen (aktuell in der Version 1.1.0 unter js-controller 3.2.8)

Ich wollte heute einmal die Aktualisierungszeit von 30s auf 60s setzen.
Ich hatte gesehen, dass im Feld "Server" kein Wert eingetragen, dem aber keine weitere Bedeutung beigemessen.
Kann es sein, das das Feld im Laufe der Entwicklung mal dazu kam?

Nachdem ich dann meine Änderung gemacht hatte, kamen nur noch die folgenden Warnings und Errors im Log:

![image](https://user-images.githubusercontent.com/25422320/105545138-09270c00-5cfc-11eb-8011-bec4026c7fd4.png)

'''
proxmox.0 | 2021-01-22 20:35:55.590 | info | (932) sendToHost not processed because States database not connected
-- | -- | -- | --
proxmox.0 | 2021-01-22 20:35:55.588 | error | (932) Cannot read property 'setState' of null
proxmox.0 | 2021-01-22 20:35:55.587 | error | at processTicksAndRejections (internal/process/task_queues.js:97:5)
proxmox.0 | 2021-01-22 20:35:55.587 | error | at Adapter.setState (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:6065:35)
proxmox.0 | 2021-01-22 20:35:55.587 | error | (932) TypeError: Cannot read property 'setState' of null
proxmox.0 | 2021-01-22 20:35:55.584 | error | (932) unhandled promise rejection: Cannot read property 'setState' of null
proxmox.0 | 2021-01-22 20:35:55.582 | error | (932) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
proxmox.0 | 2021-01-22 20:35:55.565 | warn | (932) get state Error: Connection is closed.
proxmox.0 | 2021-01-22 20:35:55.564 | warn | (932) get state Error: Connection is closed.
proxmox.0 | 2021-01-22 20:35:55.564 | warn | (932) get state Error: Connection is closed.
proxmox.0 | 2021-01-22 20:35:55.564 | warn | (932) get state Error: Connection is closed.
proxmox.0 | 2021-01-22 20:35:55.563 | warn | (932) get state Error: Connection is closed.
proxmox.0 | 2021-01-22 20:35:55.563 | warn | (932) get state Error: Connection is closed.
proxmox.0 | 2021-01-22 20:35:55.562 | warn | (932) get state Error: Connection is closed.
proxmox.0 | 2021-01-22 20:35:55.553 | warn | (932) get state Error: Connection is closed.
proxmox.0 | 2021-01-22 20:35:55.553 | warn | (932) get state Error: Connection is closed.
proxmox.0 | 2021-01-22 20:35:55.552 | warn | (932) get state Error: Connection is closed.
proxmox.0 | 2021-01-22 20:35:55.552 | warn | (932) get state Error: Connection is closed.
proxmox.0 | 2021-01-22 20:35:55.552 | warn | (932) get state Error: Connection is closed.
proxmox.0 | 2021-01-22 20:35:55.551 | warn | (932) get state Error: Connection is closed.
proxmox.0 | 2021-01-22 20:35:55.550 | warn | (932) get state Error: Connection is closed.
proxmox.0 | 2021-01-22 20:35:55.542 | warn | (932) get state Error: Connection is closed.
proxmox.0 | 2021-01-22 20:35:55.542 | warn | (932) get state Error: Connection is closed.
proxmox.0 | 2021-01-22 20:35:55.541 | warn | (932) get state Error: Connection is closed.
proxmox.0 | 2021-01-22 20:35:55.540 | warn | (932) get state Error: Connection is closed.
proxmox.0 | 2021-01-22 20:35:55.540 | warn | (932) get state Error: Connection is closed.
proxmox.0 | 2021-01-22 20:35:55.539 | warn | (932) get state Error: Connection is closed.
proxmox.0 | 2021-01-22 20:35:55.535 | warn | (932) get state Error: Connection is closed.
proxmox.0 | 2021-01-22 20:35:55.534 | warn | (932) get state Error: Connection is closed.
proxmox.0 | 2021-01-22 20:35:54.987 | info | (932) Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
proxmox.0 | 2021-01-22 20:35:54.985 | info | (932) terminating
proxmox.0 | 2021-01-22 20:35:54.979 | info | (932) cleaned everything up...
host.beebox(iobrokerMaster) | 2021-01-22 20:35:54.962 | info | stopInstance system.adapter.proxmox.0 send kill signal
proxmox.0 | 2021-01-22 20:35:54.951 | info | (932) Got terminate signal TERMINATE_YOURSELF
host.beebox(iobrokerMaster) | 2021-01-22 20:35:54.930 | info | stopInstance system.adapter.proxmox.0 (force=false, process=true)
'''

Ich hatte dann mal versucht "pve" unter Server auszwählen aber es wird nicht gespeichert.
Es kommt immer nur folgende Fehlermeldung. Die Benutzerdaten sind korrekt. Ich hab auch schon versucht ungültige Daten und danach wieder die richtigen Daten einzugeben aber ohne Erfolg.

```
2021-01-22 20:36:01.864 - info: javascript.0 (10389) script.js.Skripte.Lueftung: Lüftung.js - Betriebszustand Lüftungsanlage:0
2021-01-22 20:36:04.406 - error: proxmox.0 (25513) Unable to authenticate with Proxmox host. Please check your credentials
2021-01-22 20:36:04.408 - info: proxmox.0 (25513) Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
2021-01-22 20:36:04.409 - error: proxmox.0 (25513) 401: wrong User data, could not log in, please try again with correct user and pw
2021-01-22 20:36:04.417 - warn: proxmox.0 (25513) State "proxmox.0.info.connection" has no existing object, this might lead to an error in future versions
2021-01-22 20:36:04.932 - info: proxmox.0 (25513) cleaned everything up...
2021-01-22 20:36:05.075 - error: host.beebox(iobrokerMaster) instance system.adapter.proxmox.0 terminated by request of the instance itself and will not be restarted, before user restarts it.

```

**Comment by Feuer-sturm** [comment]
Ich bekomme die Instanz wieder zum Laufen, wenn ich nach dem Ändern des Intervalls wieder PAM bei Server auswähle und das Passwort erneut eingebe. Gebe ich das Passwort nicht neu ein (obwohl die Punkte noch da sind) scheitert die Authentifizierung.

Folgende Punkte sind dennoch auffällig:
-  Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
- Serverauswahl bleibt nicht erhalten
- Erneute Passworteingabe bei mir notwendig, damit sich Proxmox wieder verbindet (obwohl im Passwortfeld die **** angezeigt werden)
