### ISSUE TITLE
Adapter crash when shutting down a certain proxmox node from cluster

### ISSUE THREAD

**Issue by Apollon77** [iobroker-community-adapters/ioBroker.proxmox#9]
All error are based from 0.1.0, so here all code links refer to this code base from 0.1.0

```
2018-09-29 08:53:59.926  - ESC[31merrorESC[39m: Caught by controller[1]: TypeError: Cannot read property 'uptime' of undefined
2018-09-29 08:53:59.927  - ESC[31merrorESC[39m: Caught by controller[1]:     at /opt/iobroker/node_modules/iobroker.proxmox/main.js:276:56
2018-09-29 08:53:59.927  - ESC[31merrorESC[39m: Caught by controller[1]:     at _get.then.data (/opt/iobroker/node_modules/iobroker.proxmox/lib/proxmox.js:42:9)
2018-09-29 08:53:59.927  - ESC[31merrorESC[39m: Caught by controller[1]:     at Request.request [as _callback] (/opt/iobroker/node_modules/iobroker.proxmox/lib/proxmox.js:119:21)
2018-09-29 08:53:59.928  - ESC[31merrorESC[39m: Caught by controller[1]:     at Request.self.callback (/opt/iobroker/node_modules/iobroker.proxmox/node_modules/request/request.js:185:22)
2018-09-29 08:53:59.928  - ESC[31merrorESC[39m: Caught by controller[1]:     at emitTwo (events.js:106:13)
2018-09-29 08:53:59.928  - ESC[31merrorESC[39m: Caught by controller[1]:     at Request.emit (events.js:191:7)
2018-09-29 08:53:59.928  - ESC[31merrorESC[39m: Caught by controller[1]:     at Request.<anonymous> (/opt/iobroker/node_modules/iobroker.proxmox/node_modules/request/request.js:1161:10)
2018-09-29 08:53:59.928  - ESC[31merrorESC[39m: Caught by controller[1]:     at emitOne (events.js:96:13)
2018-09-29 08:53:59.931  - ESC[31merrorESC[39m: Caught by controller[1]:     at Request.emit (events.js:188:7)
2018-09-29 08:53:59.931  - ESC[31merrorESC[39m: Caught by controller[1]:     at IncomingMessage.<anonymous> (/opt/iobroker/node_modules/iobroker.proxmox/node_modules/request/request.js:1083:12)
```
https://github.com/MeisterTR/ioBroker.proxmox/blob/d77717da053c4da53975b288eff5d2c61713f0ac/main.js#L276 ... seems that the node is there in this case in json but without data (because offline). Should be checked.

```
2018-09-29 08:55:04.686  - ESC[31merrorESC[39m: Caught by controller[2]: TypeError: Cannot read property 'name' of undefined
2018-09-29 08:55:04.686  - ESC[31merrorESC[39m: Caught by controller[2]:     at /opt/iobroker/node_modules/iobroker.proxmox/main.js:310:79
2018-09-29 08:55:04.686  - ESC[31merrorESC[39m: Caught by controller[2]:     at _get.then.data (/opt/iobroker/node_modules/iobroker.proxmox/lib/proxmox.js:54:9)
2018-09-29 08:55:04.686  - ESC[31merrorESC[39m: Caught by controller[2]:     at Request.request [as _callback] (/opt/iobroker/node_modules/iobroker.proxmox/lib/proxmox.js:119:21)
2018-09-29 08:55:04.687  - ESC[31merrorESC[39m: Caught by controller[2]:     at Request.self.callback (/opt/iobroker/node_modules/iobroker.proxmox/node_modules/request/request.js:185:22)
2018-09-29 08:55:04.687  - ESC[31merrorESC[39m: Caught by controller[2]:     at emitTwo (events.js:106:13)
2018-09-29 08:55:04.687  - ESC[31merrorESC[39m: Caught by controller[2]:     at Request.emit (events.js:191:7)
2018-09-29 08:55:04.687  - ESC[31merrorESC[39m: Caught by controller[2]:     at Request.<anonymous> (/opt/iobroker/node_modules/iobroker.proxmox/node_modules/request/request.js:1161:10)
2018-09-29 08:55:04.688  - ESC[31merrorESC[39m: Caught by controller[2]:     at emitOne (events.js:96:13)
2018-09-29 08:55:04.688  - ESC[31merrorESC[39m: Caught by controller[2]:     at Request.emit (events.js:188:7)
2018-09-29 08:55:04.688  - ESC[31merrorESC[39m: Caught by controller[2]:     at IncomingMessage.<anonymous> (/opt/iobroker/node_modules/iobroker.proxmox/node_modules/request/request.js:1083:12)
```
and seems same for VMs on this node :-)
https://github.com/MeisterTR/ioBroker.proxmox/blob/d77717da053c4da53975b288eff5d2c61713f0ac/main.js#L310

**Comment by Apollon77** [comment]
The change will not fix this ... Error is e.g. node_vals.uptime is Cannot read property 'uptime' of undefined ... means node_vals itself in undefined!!! Your check will produce the same exception. SO you need to check if node_vals === undefined ... same for the second one :-)

**Comment by Apollon77** [comment]
Did you saw this?

**Comment by MarkSau** [comment]
I have the same issue since I build my cluster.....
because this issue is open since 10.218 I assume the developer does not seem to have time or interest to working on it. This is a pity, because the adapter is quite useful.

**Comment by MeisterTR** [comment]
Can you try the git version, apollon fixed it a few days ago

**Comment by MarkSau** [comment]
no success....

proxmox.0 | 2019-02-15 18:48:24.035 | error | at IncomingMessage.<anonymous> (/opt/iobroker/node_modules/request/request.js:1083:12)
-- | -- | -- | --
proxmox.0 | 2019-02-15 18:48:24.035 | error | at Request.emit (events.js:211:7)
proxmox.0 | 2019-02-15 18:48:24.035 | error | at emitOne (events.js:116:13)
proxmox.0 | 2019-02-15 18:48:24.035 | error | at Request.<anonymous> (/opt/iobroker/node_modules/request/request.js:1161:10)
proxmox.0 | 2019-02-15 18:48:24.035 | error | at Request.emit (events.js:214:7)
proxmox.0 | 2019-02-15 18:48:24.035 | error | at emitTwo (events.js:126:13)
proxmox.0 | 2019-02-15 18:48:24.035 | error | at Request.self.callback (/opt/iobroker/node_modules/request/request.js:185:22)
proxmox.0 | 2019-02-15 18:48:24.035 | error | at Request.request [as _callback] (/opt/iobroker/node_modules/iobroker.proxmox/lib/proxmox.js:117:21)
proxmox.0 | 2019-02-15 18:48:24.035 | error | at _get.then.data (/opt/iobroker/node_modules/iobroker.proxmox/lib/proxmox.js:42:9)
proxmox.0 | 2019-02-15 18:48:24.035 | error | at /opt/iobroker/node_modules/iobroker.proxmox/main.js:218:27
proxmox.0 | 2019-02-15 18:48:24.035 | error | TypeError: Cannot read property 'uptime' of undefined
proxmox.0 | 2019-02-15 18:48:24.035 | error | uncaught exception: Cannot read property 'uptime' of undefined
proxmox.0 | 2019-02-15 18:48:24.030 | debug | Request states for node MSHMCCU

**Comment by MeisterTR** [comment]
please try again i add some debug informations.

**Comment by MarkSau** [comment]
here the output of the logfile
[proxmox_debug.txt](https://github.com/iobroker-community-adapters/ioBroker.proxmox/files/2870428/proxmox_debug.txt)

**Comment by MarkSau** [comment]
i have to add the info that the failing node is only a quorum node and not a full size proxmox node. maybe this is the main issue in my case.
to explain this see https://blog.halnet.cloud/proxmox_add_a_raspberrypi_as_a_third_node/

**Comment by MeisterTR** [comment]
is there also an error when the pi is online?

**Comment by MarkSau** [comment]
sorry for the delay...Unfortunately yes, because the pi is only a quorum node and not a proxmox server

**Comment by MarkSau** [comment]
![image](https://user-images.githubusercontent.com/22911084/52910653-f9465800-329a-11e9-9f80-1d0cbdb0879d.png)

**Comment by MeisterTR** [comment]
please try again from git.

**Comment by MarkSau** [comment]
Looks very good now.. Adapter is running without errors. Good job..will check in detail tomorrow from my PC..because I'm currently in my mobile..




Outlook für Android herunterladen







On Sun, Feb 17, 2019 at 9:26 PM +0100, "MeisterTR" <notifications@github.com> wrote:












please try again from git.

**Comment by MarkSau** [comment]
Looks very fine. All Nodes and VMs objects are available. good job, thx
